// =============================================
// AI Platform - Types Barrel
// =============================================
//
// This file is now a barrel that re-exports types from the canonical
// source of truth: `./database.types.ts` (which mirrors `supabase/schema.sql`).
//
// Historically there were two parallel type trees here (database.types.ts
// and a custom index.ts) — they drifted apart and caused runtime bugs.
// The custom types have been merged into database.types.ts and this file
// now only re-exports them under friendlier names.
//
// To regenerate database.types.ts from a live Supabase instance run:
//   supabase gen types typescript --local > src/types/database.types.ts
// =============================================

export * from './database.types';

// Re-export commonly-used types under shorter aliases
export type {
  // Database tables (canonical Row types)
  Category as Category,
  Tool as Tool,
  Profile as Profile,
  Review as Review,
  Article as Article,
  Favorite as Favorite,
  NewsletterSubscriber as NewsletterSubscriber,
  ApiKey as ApiKey,

  // Convenience helpers
  Database as Database,
} from './database.types';

// ============================================================================
// App-level helpers (NOT generated by Supabase)
// ============================================================================

import type { Database } from './database.types';

// Row-type helper to avoid duplicating the Database['public']['Tables'] drill
type TableRow<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
type CategoryRow = TableRow<'categories'>;

// A user as exposed to the React client.
// Built from auth.users + profiles.role, never from user_metadata.
export interface AppUser {
  id: string;
  email: string;
  name: string;
  username?: string;
  avatar_url?: string;
  bio?: string;
  plan: 'free' | 'starter' | 'pro' | 'enterprise';
  role: 'viewer' | 'editor' | 'admin' | 'super_admin';
}

// API response envelope
export interface ApiResponse<T> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

export interface PaginatedResponse<T> {
  data: T[];
  meta: {
    total: number;
    page: number;
    limit: number;
    total_pages: number;
  };
}

// Recursive category (Supabase doesn't synthesize `children` automatically;
// callers assemble it via parent_id traversal).
export interface CategoryWithChildren extends CategoryRow {
  children?: CategoryWithChildren[];
}
